### ISSUE TITLE
Issue importing g2s for Python

### ISSUE THREAD

**Issue by marinxm** [GAIA-UNIL/Short-course-MPS#1]
When trying to import g2s into python after installing g2s through pip I get,

from g2s import g2s
ImportError                               Traceback (most recent call last)
[<ipython-input-1-25bc5713c8a8>](https://localhost:8080/#) in <module>
----> 1 from g2s import g2s
      2 g2s('--version')

[/usr/local/lib/python3.8/dist-packages/g2s/__init__.py](https://localhost:8080/#) in <module>
     10                 os.environ['PATH'] += os.pathsep + extra_dll_dir
     11 
---> 12 from .g2s import run
     13 from .g2s import run as g2s

ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/local/lib/python3.8/dist-packages/g2s/g2s.cpython-38-x86_64-linux-gnu.so)
@gregoiremariethoz @pauwiersma

**Comment by mgravey** [comment]
Hi I can reproduce the bug, I will look to fix this

**Comment by marinxm** [comment]
> 嗨，我可以重现这个错误，我会修复这个问题

thank you. @mgravey

**Comment by mgravey** [comment]
@marinxm, it's fix sorry for inconvenience
